services:
  db:
    container_name: db
    image: "mongo:4"
    ports:
      - 27017:27017
    networks:
      - custom

  back:
    container_name: back
    build: back/
    ports:
      - 16001:5000
    networks:
      - custom
    depends_on:
      - db
    environment:
      MONGO_CONNECTION: "mongodb://localhost:27017/test"


  client:
    container_name: client
    build: nuxt/
    ports:
      - 16002:3000
    networks:
      - custom
    environment:
      API_URL: "http://back:5000"

networks:
  custom:
    driver: bridge
