services:
  db:
    container_name: db
    image: "mongo:latest"
    ports:
      - 16017:27017
    networks:
      - custom

  back:
    container_name: back
    build: back/
    ports:
      - 16001:5000
    networks:
      - custom
    depends_on:
      - db
    environment:
      MONGO_CONNECTION: "mongodb://db:27017/test"


  client:
    container_name: client
    build: nuxt/
    ports:
      - 16002:3000
    networks:
      - custom

  ml:
    container_name: ml
    build: ml/
    ports:
      - 16003:8000
    environment:
      - CUDA_VISIBLE_DEVICES=-1
    networks:
      - custom

networks:
  custom:
    driver: bridge
